site_name: USHCN Temperature Data Analysis Tool
site_url: https://rjl-climate.github.io/ushcn-analysis-tool/
site_description: Python library for analysing USHCN temperature data
site_author: Richard Lyon

repo_url: https://github.com/rjl-climate/ushcn-analysis-tool
repo_name: ushcn-analysis-tool

theme:
  name: readthedocs
  locale: en

nav:
  - Home: index.md
  - Research Studies:
      - Overview: studies/index.md
      - UHI Contamination: studies/uhi-contamination.md

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          options:
            show_source: true

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.tabbed:
      alternate_style: true
  - tables
  - toc:
      permalink: true
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.arithmatex:
      generic: true

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/rjl-climate/ushcn-analysis-tool
